src/main/java/com/ssginc/showpinglive/config/WebSocketConfig.java, src/main/java/com/ssginc/showpinglive/handler/LiveHandler.java, src/main/java/com/ssginc/showpinglive/handler/RecordHandler.java, src/main/java/com/ssginc/showpinglive/util/UserRegistry.java, src/main/java/com/ssginc/showpinglive/util/UserSession.java, src/main/resources/static/css/webrtc/kurento.css, src/main/resources/static/js/stream.js, src/main/resources/templates/webrtc/webrtc.html
***
- WebRTC로 VOD 재생을 위한 송출시 녹화기능 구현
- RecorderEndPoint 활용 녹화 구현
- 녹화를 위한 WebSocket 셋팅
- 라이브 종료 후 VOD mp4 파일 생성
***
- #7
=> Feat: 라이브 녹화 기능 구현

src/main/java/com/ssginc/showpinglive/controller/StreamController.java, src/main/java/com/ssginc/showpinglive/controller/WatchController.java, src/main/java/com/ssginc/showpinglive/controller/WebRtcController.java, src/main/java/com/ssginc/showpinglive/dto/response/VodResponseDto.java, src/main/java/com/ssginc/showpinglive/repository/StreamRepository.java, src/main/java/com/ssginc/showpinglive/service/StreamService.java, src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java, src/main/resources/static/css/watch/vod.css, src/main/resources/static/js/stream.js, src/main/resources/static/js/vod.js, src/main/resources/templates/layout.html, src/main/resources/templates/watch/vod.html, src/main/resources/templates/webrtc/watch.html
- 라이브.VOD 시청 구현
***
- VOD. 라이브 시청 페이지 구현
- 저장된 VOD 불러오는 API 작성
- 라이브 시청 js 구현
***
- #13
=> Feat: 영상 시청 구현

build.gradle, src/main/java/com/ssginc/showpinglive/config/NCPConfig.java, src/main/java/com/ssginc/showpinglive/controller/StreamController.java, src/main/java/com/ssginc/showpinglive/service/StreamService.java, src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java, src/main/resources/static/js/stream.js
***
- 로컬에서의 VOD 관리 Local Storatge -> NCP Storage로 구현
- NCP 스토리지 설정
- 녹화본 저장 후 NCP로 mp4 파일 전송
- NCP에서 VOD 불러오는 로직 변경
***
- #20
=> Feat: NCP Storage 로직 구현

src/main/java/com/ssginc/showpinglive/controller/StreamController.java, src/main/java/com/ssginc/showpinglive/service/StreamService.java, src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java, src/main/resources/static/js/vod.js, src/main/resources/templates/watch/vod.html
- HLS 기반 VOD 스트리밍 구현
***
- #22
=> Feat: VOD HLS 스트리밍 구현

src/main/java/com/ssginc/showpinglive/service/KafkaConsumerService.java, src/main/java/com/ssginc/showpinglive/service/KafkaProducerService.java, src/main/java/com/ssginc/showpinglive/service/implement/KafkaConsumerServiceImpl.java, src/main/java/com/ssginc/showpinglive/service/implement/KafkaProducerServiceImpl.java
Kafka Producer 서비스 분리
Kafka Consumer 서비스 분리
=> Refactor: kafka service 분리

src/main/java/com/ssginc/showpinglive/api/Segments.java, src/main/java/com/ssginc/showpinglive/api/StorageLoader.java, src/main/java/com/ssginc/showpinglive/api/SubtitleGenerator.java, src/main/java/com/ssginc/showpinglive/api/Words.java, src/main/java/com/ssginc/showpinglive/config/NCPConfig.java, src/main/java/com/ssginc/showpinglive/config/WebSocketConfig.java, src/main/java/com/ssginc/showpinglive/controller/StreamController.java, src/main/java/com/ssginc/showpinglive/controller/WatchController.java, src/main/java/com/ssginc/showpinglive/handler/LiveHandler.java, src/main/java/com/ssginc/showpinglive/handler/RecordHandler.java, src/main/java/com/ssginc/showpinglive/repository/StreamRepository.java, src/main/java/com/ssginc/showpinglive/repository/WatchRepository.java, src/main/java/com/ssginc/showpinglive/service/StreamService.java, src/main/java/com/ssginc/showpinglive/service/SubtitleService.java, src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java, src/main/java/com/ssginc/showpinglive/service/implement/SubtitleServiceImpl.java, src/main/resources/static/css/watch/vod.css, src/main/resources/static/js/watch/vod.js, src/main/resources/templates/watch/vod.html
- VOD 자막 구현
***
- mp4파일에서 자막정보 json 파일을 저장하는 API 구현
- json 자막정보 파일을 불러오는 API 구현
- html video 태그에 자막 포함
- 자막활성화 여부에 따른 자막표시 구현
- 영상 시간에 따른 동적으로 자막 생성 구현
***
- #36
=> Feat: VOD 자막기능 구현

src/main/java/com/ssginc/showpinglive/controller/ChatRoomController.java, src/main/java/com/ssginc/showpinglive/dto/response/ChatRoomResponseDto.java, src/main/java/com/ssginc/showpinglive/service/ChatRoomService.java, src/main/java/com/ssginc/showpinglive/service/implement/ChatRoomServiceImpl.java, src/main/resources/static/js/chat/chatRoom.js
=> Feat: 채팅방 등록 API 구현

src/main/java/com/ssginc/showpinglive/controller/ChatController.java, src/main/java/com/ssginc/showpinglive/service/implement/ChatServiceImpl.java, src/main/resources/static/js/stream/stream.js
- ChatController
- Stream.js
- ChatServiceImpl
=> Refactor: 채팅 리팩토링

src/main/java/com/ssginc/showpinglive/controller/WebRtcController.java, src/main/resources/static/css/watch/stream.css, src/main/resources/static/js/stream/list.js, src/main/resources/static/js/stream/stream.js, src/main/resources/templates/layout.html, src/main/resources/templates/webrtc/watch.html
=> Refactor: 시청 측 로직 리팩토링

src/main/java/com/ssginc/showpinglive/controller/ReportController.java, src/main/java/com/ssginc/showpinglive/dto/response/ReportResponseDto.java, src/main/java/com/ssginc/showpinglive/service/implement/ReportServiceImpl.java, src/main/resources/static/js/report/report.js, src/main/resources/templates/report/report.html
=> Refactor: 신고 관리 상세정보 리팩토링

src/main/java/com/ssginc/showpinglive/controller/MemberController.java, src/main/java/com/ssginc/showpinglive/repository/MemberRepository.java, src/main/java/com/ssginc/showpinglive/service/AuthService.java, src/main/java/com/ssginc/showpinglive/service/implement/AuthServiceImpl.java, src/main/resources/static/js/login/logout.js, src/main/resources/static/js/login/signup.js
- 그외 자잘한 수정으로 관리자 아이디가 로그아웃 될때 세션스토리지의 memberId가 삭제되는 로직 추가
=> Chore: 회원가입 과정에서 이메일 중복 유효성 검사 체크 로직 추가

src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java, src/main/java/com/ssginc/showpinglive/controller/WatchController.java, src/main/java/com/ssginc/showpinglive/handler/RecordHandler.java, src/main/java/com/ssginc/showpinglive/jwt/JwtFilter.java, src/main/java/com/ssginc/showpinglive/repository/StreamRepository.java, src/main/resources/static/css/watch/stream.css, src/main/resources/static/js/stream/stream.js, src/main/resources/static/js/watch/history.js, src/main/resources/templates/layout.html, src/main/resources/templates/watch/history.html
- 세션 스토리지 구현에 따른 axios에 header 추가 (시청내역 확인)
- VOD CSS 수정
- VOD 생성될 파일명 변경
=> Refactor: 프로젝트 리팩토링

src/main/java/com/ssginc/showpinglive/controller/ChatController.java, src/main/java/com/ssginc/showpinglive/controller/ReportController.java, src/main/java/com/ssginc/showpinglive/dto/request/ReportRegisterRequestDto.java, src/main/java/com/ssginc/showpinglive/service/ReportService.java, src/main/java/com/ssginc/showpinglive/service/implement/ReportServiceImpl.java, src/main/resources/static/js/stream/stream.js, src/main/resources/templates/webrtc/webrtc.html
- 채팅 신고 등록
- memberId, memberRole 토큰 사용
- #69
=> Refactor: 채팅 신고 등록

src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java, src/main/java/com/ssginc/showpinglive/config/WebSocketAuthInterceptorConfig.java, src/main/java/com/ssginc/showpinglive/config/WebSocketChatConfig.java, src/main/java/com/ssginc/showpinglive/config/WebsocketUserInterceptorConfig.java, src/main/java/com/ssginc/showpinglive/controller/ChatController.java, src/main/java/com/ssginc/showpinglive/handler/UserCustomHandshakeHandler.java, src/main/java/com/ssginc/showpinglive/jwt/JwtFilter.java, src/main/java/com/ssginc/showpinglive/repository/ForbiddenWordRepository.java, src/main/resources/static/js/report/report.js, src/main/resources/static/js/stream/stream.js, src/main/resources/templates/report/report.html, src/main/resources/templates/webrtc/watch.html, src/main/resources/templates/webrtc/webrtc.html
=> Refactor : 채팅 금칙어 리팩토링

src/main/java/com/ssginc/showpinglive/controller/HlsController.java, src/main/java/com/ssginc/showpinglive/service/HlsService.java, src/main/java/com/ssginc/showpinglive/service/implement/HlsServiceImpl.java
=> Feat: 성능테스트 시나리오 구현

src/main/java/com/ssginc/showpinglive/controller/StreamController.java, src/main/java/com/ssginc/showpinglive/controller/WebRtcController.java, src/main/java/com/ssginc/showpinglive/dto/response/GetStreamProductInfoResponseDto.java, src/main/java/com/ssginc/showpinglive/service/StreamService.java, src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java, src/main/resources/static/css/watch/stream.css, src/main/resources/static/js/stream/get_stream_info.js, src/main/resources/static/js/stream/register_stream.js, src/main/resources/static/js/stream/stream.js, src/main/resources/templates/webrtc/watch.html, src/main/resources/templates/webrtc/webrtc.html
- 라이브 시청 UI 구현
- 라이브 시청시 상품 정보 조회 구현
***
- #65
=> Feat: 라이브 시청 UI 및 상품 정보 조회 구현

src/main/resources/static/js/stream/stream.js, src/main/resources/static/js/stream/watch.js, src/main/resources/templates/webrtc/watch.html
=> Fix: 라이브 시청 버그 수정

src/main/resources/static/js/stream/get_stream_info.js, src/main/resources/static/js/stream/list.js, src/main/resources/static/js/stream/product_modal.js, src/main/resources/static/js/stream/register_stream.js, src/main/resources/static/js/stream/stream.js, src/main/resources/templates/webrtc/watch.html
=> Refactor: 라이브 코드 리팩토링

src/main/java/com/ssginc/showpinglive/controller/WebRtcController.java, src/main/resources/static/js/stream/stream.js, src/main/resources/templates/webrtc/watch.html, src/main/resources/templates/webrtc/webrtc.html
=> Refactor: 비로그인, 공지, 채팅신고 리팩토링

src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java, src/main/java/com/ssginc/showpinglive/controller/WatchController.java, src/main/java/com/ssginc/showpinglive/dto/request/WatchRequestDto.java, src/main/java/com/ssginc/showpinglive/service/WatchService.java, src/main/java/com/ssginc/showpinglive/service/implement/WatchServiceImpl.java, src/main/resources/static/css/stream/stream.css, src/main/resources/static/css/watch/history.css, src/main/resources/static/js/stream/list.js, src/main/resources/static/js/watch/history.js, src/main/resources/static/js/watch/vod.js, src/main/resources/templates/watch/history.html, src/main/resources/templates/watch/vod.html
=> Refactor: VOD 관련 리팩토링

src/main/java/com/ssginc/showpinglive/controller/StreamController.java, src/main/java/com/ssginc/showpinglive/dto/response/StreamResponseDto.java, src/main/java/com/ssginc/showpinglive/repository/StreamRepository.java, src/main/java/com/ssginc/showpinglive/service/StreamService.java, src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java, src/main/resources/static/css/stream/stream.css, src/main/resources/static/css/style.css, src/main/resources/static/js/stream/list.js, src/main/resources/templates/layout.html, src/main/resources/templates/stream/list.html
- 라이브 페이지 대대적으로 스타일링 수정...
***
- #108
=> Feat: 라이브 메인페이지 수정

src/main/resources/static/css/watch/stream.css, src/main/resources/static/js/stream/stream.js, src/main/resources/templates/webrtc/watch.html, src/main/resources/templates/webrtc/webrtc.html
=> Refactor : 채팅 UI, FAQ

src/main/java/com/ssginc/showpinglive/controller/StreamController.java, src/main/java/com/ssginc/showpinglive/repository/StreamRepository.java, src/main/java/com/ssginc/showpinglive/service/StreamService.java, src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java
=> Feat: 메인페이지 VOD API 구현

src/main/resources/static/js/stream/stream.js
=> Fix: 시청측 웹소켓 수정

src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java, src/main/java/com/ssginc/showpinglive/controller/ChatController.java, src/main/java/com/ssginc/showpinglive/dto/object/ChatDto.java, src/main/java/com/ssginc/showpinglive/repository/ChatRepository.java, src/main/java/com/ssginc/showpinglive/service/ChatService.java, src/main/java/com/ssginc/showpinglive/service/implement/ChatServiceImpl.java, src/main/resources/static/js/stream/stream.js, src/main/resources/static/js/watch/vod.js, src/main/resources/templates/watch/vod.html, src/main/resources/templates/webrtc/watch.html, src/main/resources/templates/webrtc/webrtc.html, src/test/java/com/ssginc/showpinglive/chat/ChatMessageIntegrationTest.java
=> Feat: VOD 채팅 확인 기능

src/main/java/com/ssginc/showpinglive/controller/ReportController.java, src/main/java/com/ssginc/showpinglive/dto/response/ReportResponseDto.java, src/main/resources/static/css/report/report.css, src/main/resources/static/js/report/report.js, src/main/resources/templates/report/report.html
- 불필요한 주석 및 디버깅 문구 제거
- 잘못 기재된 코드 정상화
=> Refactor: 신고 관리 리팩토링

src/main/resources/static/js/stream/stream.js
- #137 
***
- 급하게 해결해야하는 이슈라 빠르게 수정...
=> Hotfix: 웹소켓 버그 수정

src/main/resources/static/js/stream/stream.js
- 괄호로 인해 파일명의 따옴표가 배포서버에 추가되는 버그 수정
=> Fix: 파일명 형식 수정

src/main/resources/static/js/watch/vod.js
=> Refactor: HLS 경로 변경

.github/workflows/gradle.yml, src/main/resources/static/css/index.css, src/main/resources/static/css/stream/stream.css, src/main/resources/static/js/report/report.js, src/main/resources/static/js/stream/stream.js, src/main/resources/templates/index.html, src/main/resources/templates/layout.html
=> Refactor: 프로젝트 최종 리팩토링
